server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: cloudproj@163.com
    password: GQKROSVAQFVACRPU
    default-encoding: utf-8
    properties:
      mail:
        debug:true #

mybatis:
  configuration:
    map-underscore-to-camel-case: true

